#+title: Collaborating though GitHub (or similar)
#+description: Zoom
#+colordes: #cc0066
#+slug: git-14-collaborating
#+weight: 15

In this interactive session, I will answer the questions you had while going through the course material, then we will collaborate on a project though GitHub. Please go through the [[https://westgrid-cli.netlify.app/school/git-13-remotes.html][Remotes]] lesson and make sure [[https://westgrid-cli.netlify.app/school/git-03-install.html#headline-4][you have a GitHub account]] before joining this interactive session.

#+BEGIN_zoombox
*This interactive session will be conducted through Zoom.*

*The meeting ID and password will be emailed to people who registered for this course.*
#+END_zoombox

Note that *no recording* will be made during this session so as not to discourage participation.

* Inviting collaborators to a GitHub repo

Go to the {{<b>}}Settings{{</b>}} tab, then the {{<b>}}Manage access{{</b>}} section on the left-hand side. Finally click {{<b>}}Invite a collaborator{{</b>}}.

* Cloning a repo from GitHub

Now, your collaborators can clone the project from GitHub to their machine to start working on it (with Git, everybody has a full version of the project and its history on their machine).

#+BEGIN_example
cd /place/where/you/want/to/have/your/project
git clone git@github.com:<user>/<repo>.git <name>
#+END_example

{{<b>}}&lt;name&gt;{{</b>}} is not necessary: this is only if you want to rename the repo on your machine.
