#+title: Version control with Git
#+slug: git

**** /Abstract/

#+BEGIN_definition
This day-long workshop introduces version control with Git and covers the most common operations. It puts a particular emphasis on explaining the functioning of Git: understanding what commands really do brings the confidence to go beyond the limited use of "add, commit, push" so common in data science fields.
#+END_definition

**** /Workshop requirements/

#+BEGIN_box
*1 - Git* \\
{{<n>}}{{<n>}}You can download Git [[https://gitforwindows.org/][here]] if you are on Windows and [[https://git-scm.com/downloads][here]] if you use MacOS or Linux.

*2 - GitLab account* \\
{{<n>}}{{<n>}}You can create a free GitLab account [[https://gitlab.com/users/sign_in?__cf_chl_jschl_tk__=d6a7eb9925781c7356331ce3eda5d0378c110295-1599623906-0-AQ1HOeAIWNL8AJ7U_v0kt3QlRK4uYA_zmS1__jAw6nO53JW6_1wp4YDAo_tVUuutDu-vl-x-lgIzHlVeSmXOQs8GcsWLBDtOe93ymvUxLHjrbXPTFOJhq5l_kAtGm3boRBhXOD3PriN6hPuTUjbx5CpI9uHsj2XMqNhJKV5TA9n5nUSIML9-c603Ch7ysTm_xHSKghlZqDcVDqMzTCWiowIHWm6r3PLwtAtRMGMMmtZFAWfELJOH0EcMtugU3GVJU_ByWuCmKv0m7GZG4X2k5cGgZ_pBFjWuKrpIfUw76RgNEBXm77UjYpfWzYloWdil1CO8fqSzQ8a7FH1hVq9oDjbJcgFkaoyq9pwj9Vv1geic#register-pane][here]].
#+END_box

**** Workshop material

This workshop is run by doing live coding within a [[https://github.com/damianavila/RISE][RISE]] presentation from a [[https://jupyter.org/][Jupyter notebook]].

With this format, making the material available outside of the actual workshop is not easy. Below are various formats, each with their pros and cons.

***** Binder

The presentation can be accessed and interacted with through Binder:

#+BEGIN_export html
<a href="https://mybinder.org/v2/gh/WestGrid/jupyter.git/master?filepath=git.ipynb" target="_blank"><img src="https://mybinder.org/badge_logo.svg"/></a>
#+END_export

This preserves the full functionality of the RISE presentation, but it takes some time to load. As binder is quite slow, it may be best to stick to watching the presentation (by pressing the Space bar) rather than trying to run the code.

***** Pdf

The presentation is also available as [[/jupyter/git.pdf][a pdf]]. While this preserves the formatting, the hyperlinks are not active on this pdf and the code is not easy to copy if you want to copy/paste.

***** Html

#+BEGIN_export html
Finally, it is available as <a href="/jupyter/git.html" target="_blank">a simple html</a>. This format is fast (unlike Binder), has code easy to copy and working hyperlinks (unlike the pdf), but it does not have the reveal.js fancy formatting of the other options.
#+END_export

* Comments & questions
