#+title: .gitignore syntax
#+description: Annex
#+colordes: #2d5986
#+slug: git-15-gitignore
#+weight: 16

#+OPTIONS: toc:nil

While writing your {{<b>}}.gitignore{{</b>}} file, you can add files to be excluded one by one. In many cases however, it is really convenient to use globing patterns to exclude many files at once. This annex presents the rules to write such patterns.

* .gitignore rules

- Each line in a {{<b>}}.gitignore{{</b>}} file specifies a pattern {{<2br>}}

- Blank lines are ignored and can serve as separators for readability {{<2br>}}

- Lines starting with {{<c>}}#{{</c>}} are comments {{<2br>}}

- To add patterns starting with a special character (e.g. {{<c>}}#{{</c>}}, {{<c>}}!{{</c>}}), that character needs escaping with {{<c>}}\{{</c>}} {{<2br>}}

- Trailing spaces are ignored unless they are escaped with {{<c>}}\{{</c>}} {{<2br>}}

- {{<c>}}!{{</c>}} negates patterns (matching files excluded by previous patterns become included again)
{{<m>}}{{<m>}} *However* it is not possible to re-include a file if one of its parent directories is excluded (Git doesn’t list {{<m>}}{{<m>}} excluded directories for performance reasons).

{{<m>}}{{<m>}} One way to go around that is to force the inclusion of a file which is in an ignored directory with the {{<m>}}{{<m>}} option {{<c>}}-f{{</c>}}.

{{<m>}}{{<m>}}{{<m>}} /Example: {{<n>}}{{<c>}}git add -f &lt;file&gt;{{</c>}}/ {{<2br>}}

- Patterns ending with {{<c>}}/{{</c>}} match directories. Otherwise patterns match both files and directories {{<2br>}}

- {{<c>}}/{{</c>}} at the beginning or within a search pattern indicates that the pattern is relative to the directory level of the {{<b>}}.gitignore{{</b>}} file. Otherwise the pattern matches anywhere below the {{<b>}}.gitignore{{</b>}} level

{{<m>}}{{<m>}}{{<m>}} /Examples:/ \\
/{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<n>}}{{<s>}}{{<s>}} - {{<c>}}foo/bar/{{</c>}} matches the directory {{<b>}}foo/bar{{</b>}}, but not the directory {{<b>}}a/foo/bar{{</b>}}/ \\
/{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<m>}}{{<n>}}{{<s>}}{{<s>}} - {{<c>}}bar/{{</c>}} matches both the directories {{<b>}}foo/bar{{</b>}} and {{<b>}}a/foo/bar{{</b>}}/ {{<2br>}}

- {{<c>}}*{{</c>}} matches anything except {{<c>}}/{{</c>}} {{<2br>}}

- {{<c>}}?{{</c>}} matches any one character except {{<c>}}/{{</c>}} {{<2br>}}

- The range notation (e.g. {{<c>}}[a-zA-Z]{{</c>}}) can be used to match one of the characters in a range {{<2br>}}

- A leading {{<c>}}**/{{</c>}} matches all directories

{{<m>}}{{<m>}}{{<m>}} /Example: {{<n>}}{{<c>}}**/foo{{</c>}} matches file or directory {{<b>}}foo{{</b>}} anywhere. This is the same as {{<c>}}foo{{</c>}}/ {{<2br>}}

- A trailing {{<c>}}/**{{</c>}} matches everything inside what it precedes

{{<m>}}{{<m>}}{{<m>}} /Example: {{<n>}}{{<c>}}abc/**{{</c>}} matches all files (recursively) inside directory {{<b>}}abc{{</b>}}/ {{<2br>}}

- {{<c>}}/**/{{</c>}} matches zero or more directories

{{<m>}}{{<m>}}{{<m>}} /Example: {{<n>}}{{<c>}}a/**/b{{</c>}} matches {{<b>}}a/b{{</b>}}, {{<b>}}a/x/b{{</b>}}, and {{<b>}}a/x/y/b{{</b>}}/

* Comments & questions
