#+title: GIS with R
#+topic: R
#+slug: gis_r
#+date: 2020-12-09
#+place: 60 min live webinar

*** /Abstract/

#+BEGIN_definition
This webinar introduces basic GIS data manipulation and mapping in R with the packages ~sf~ and ~tmap~.

We will use data on the retreat of North American glaciers as an example.
#+END_definition

* Datasets

A good starting place to look for open source GIS datasets is the  [[https://freegisdata.rtwilson.com/][Free GIS Data]] page.

The datasets that we will use for this webinars are the Alaska and the Western Canada and USA subsets of the [[http://www.glims.org/RGI/][Randolph Glacier Inventory]] version 6.0{{<fl n="1">}} and the [[https://www.sciencebase.gov/catalog/item/58af7022e4b01ccd54f9f542][USGS time series of the named glaciers of Glacier National Park]]{{<fl n="2">}}. These datasets can be downloaded as zip files from the respective websites.

For our basemap, we will use data from [[https://www.naturalearthdata.com/][Natural Earth]]. This dataset can be accessed direction from within R thanks to the packages ~rnaturalearth~ (which provides the functions) and ~rnaturalearthdata~ (which provides the data).

{{<fn>}}
{{<fl n="1">}}RGI Consortium (2017). Randolph Glacier Inventory – A Dataset of Global Glacier Outlines: Version 6.0: Technical Report, Global Land Ice Measurements from Space, Colorado, USA. Digital Media. DOI: https://doi.org/10.7265/N5-RGI-60.{{<2br>}}
{{<fl n="2">}}Fagre, D.B., McKeon, L.A., Dick, K.A., and Fountain, A.G., 2017, Glacier margin time series (1966, 1998, 2005, 2015) of the named glaciers of Glacier National Park, MT, USA: U.S. Geological Survey data release, https://doi.org/10.5066/F7P26WB1.
{{</fn>}}

* Load necessary packages

#+BEGIN_src R
library(sf)
library(tmap)
library(dplyr)
library(magrittr)
library(purrr)
library(rnaturalearth)
library(rnaturalearthdata)
library(grid)
#+END_src

* Video

{{<ytmh vWwbwROqn6w>}}

* Comments & questions
